# -*- coding: utf-8 -*-
"""ISTA_322_Su25_HW3_SQL_cougar_bellinger.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZlCLXLlEPNkB1rDAY0OPN27bGAIBwtLS

# Reminder: Submission Instructions

1) First create a copy of this notebook in your drive and rename it so that it contains the course number (ISTA322), the semester (Sp22 for Spring 2022, Su22 for Summer 2022, and Fa22 for Fall 2022), the assigment code (HW1 for this assignment) and your name.

    e.g. my copy for Spring 2023 would be ISTA_322_Sp23_HW3_dan_charbonneau)

2) When you are ready to submit. Prepare three files: the python file (File->Download->Download .py), the notebook file (File->Download->Download .ipynb), and **PDF** version of your notebook (**after running all cells**). You should be able to create a pdf through File -> print -> Destination: save as pdf

3) Create a new folder named firstname_lastname_hw1 (e.g my folder would be dan_charbonneau_hw3) put all three files in it. Compress (Zip) the folder you created with the files inside of it and submit this .zip file to D2L

**incorrect filenames or submission formats will result in a loss of 50% of your grade**

#HW3 - SQL

This homework has you working with a new database of information on ticket sales for various types of events.  Your job will be to do some initial exploring and then demonstrate your ability to do all the different types of SQL queries we learned over the last two week.  You'll also need to make one function that'll make looking at the tables easier.

These questions are written in the way someone would ask them to you.  In other words, I'm using 'plain english' questions vs. ones where I'm very explicit in terms of what columns and tables to use.  Your exploring of the database and functions to ease that process will come in handy here!  

The database has been created using a set of data from Amazon. You can read more about what each table contains here: https://docs.aws.amazon.com/redshift/latest/dg/c_sampledb.html.

## Libraries and import functions

First bring the libraries we'll need!
"""

import psycopg2
import pandas as pd

"""Now bring in all our functions we used in the lessons!  """

# Make our connection/cursor function
AWS_host_name = "ista322courserdb.chk8kg2yo4p6.us-east-1.rds.amazonaws.com"
AWS_dbname = "ista322courserdb"
AWS_user_name = "postgres"
AWS_password = "orangecatgoingnutsinacardboardbox"

def get_conn_cur(): # define function name and arguments (there aren't any)
  # Make a connection
  conn = psycopg2.connect(
    host=AWS_host_name,
    database=AWS_dbname,
    user=AWS_user_name,
    password=AWS_password,
    port='5432')

  cur = conn.cursor()   # Make a cursor after

  return(conn, cur)   # Return both the connection and the cursor

# Same run_query function


# Column name function for checking out what's in a table
def get_column_names(table_name): # arguement of table_name
  conn, cur = get_conn_cur() # get connection and cursor

  # Now select column names while inserting the table name into the WERE
  column_name_query =  """SELECT column_name FROM information_schema.columns
       WHERE table_name = '%s' """ %table_name

  cur.execute(column_name_query) # exectue
  my_data = cur.fetchall() # store

  cur.close() # close
  conn.close() # close

  return(my_data) # return

# Check table_names
def get_table_names():
  conn, cur = get_conn_cur() # get connection and cursor

  # query to get table names
  table_name_query = """SELECT table_name FROM information_schema.tables
       WHERE table_schema = 'public' """

  cur.execute(table_name_query) # execute
  my_data = cur.fetchall() # fetch results

  cur.close() #close cursor
  conn.close() # close connection

  return(my_data) # return your fetched results

"""## Q1 Make a SQL head function - 5 point

Make function to get the pandas equivalent of `.head()`

This function should be called `sql_head` and take a single argument of `table_name` where you specify the table name you want the head information from.  It should return the column names along with the first five rows of the table along.  

**For full points, return a pandas dataframe with this information so it displays nicely :)**
"""

## Q1 Your function starts here
def sql_head(table_name, n=5):
    query = f"SELECT * FROM {table_name} LIMIT {n};"
    colnames, my_data = run_query(query)
    df = pd.DataFrame(my_data, columns=colnames)

    return df
# make sql_head function
get_table_names()

# Check that it works!
sql_head(table_name = 'sales')
## Q1 Your function ends here - Any code outside of these start/end markers won't be graded

"""## Q2 Explore and SELECT - 5 point

Let's start this homework with some basic queries to get a look at what's in the various tables.  I want you to do the following.

* Use your get_table_names() function to see what tables are in the database.
* Use your get_column_names() to get the column names of each of the tables.  **Do this all within a single cell to keep it neat**.
* Make and run a query that selects all columns from the event table.  Only return the first 5 rows.
* Use the `sql_head()` function you created to get the first five rows of the sales table.
"""

## Q2 Your function starts here
# Getting table names
get_table_names()

# Getting column names
movie_cols = get_column_names(table_name='movie_sales')
rollup_cols = get_column_names(table_name='rollup')
creators_cols = get_column_names(table_name='creators')
teams_df_cols = get_column_names(table_name='teams_df')
cases_cols = get_column_names(table_name='cases')
season_stats_df_cols = get_column_names(table_name='season_stats_df')
spotify_features_cols = get_column_names(table_name='spotify_features')
death_data_cols = get_column_names(table_name='death_data')
judges_cols = get_column_names(table_name='judges')
songs_cols = get_column_names(table_name='songs')
referees_df_cols = get_column_names(table_name='referees_df')
sales_cols = get_column_names(table_name='sales')
venue_cols = get_column_names(table_name='venue')
event_cols = get_column_names(table_name='event')
users_cols = get_column_names(table_name='users')
category_cols = get_column_names(table_name='category')
listing_cols = get_column_names(table_name='listing')
date_cols = get_column_names(table_name='date')
game_data_df_cols = get_column_names(table_name='game_data_df')
movies_cols = get_column_names(table_name='movies')
ratings_cols = get_column_names(table_name='ratings')
casetyp_cols = get_column_names(table_name='casetyp')


# ...
# ...
# ...
# ...

# Could also just use a list comprehension vs a bunch of print statements :)
names = get_table_names()
[get_column_names(table_name= x) for x in names]

# Query on events
sq = """SELECT * FROM event LIMIT 5"""
run_query(sq)

# Use sql_head to get the head of sales
sql_head(table_name='sales')

# Debugging
sql_head(table_name='users')
## Q2 Your function ends here - Any code outside of these start/end markers won't be graded

"""## Q3 WHERE - 5 points

Now let's do a bit of filtering with WHERE.  Write and run queries to get the following results.  
**LIMIT all returns to first five rows.**

* Get venues (**full row of data, including venue_id, etc.**) with >= 10000 seats from the venues table
* Get venues (**full row of data, including venue_id, etc.**) in Arizona
* Get users (**just the first names**) who have a first name that starts with H
* Get the email addresses (**just the email addresses**) of users who gave a .edu email address

**Make sure to use the sq1, sq2, and sq3 as variables to store your queries in because those will specifically be evaluated**

"""

## Q3 Your function starts here
# Get big venues... so those with >= than 10000 seats
sq1 = """ SELECT * FROM venue WHERE venue_seats >= 10000"""
run_query(sq1)

# Get venues in AZ
sq2 = """ SELECT * FROM venue WHERE venue_state = 'AZ';"""
run_query(sq2)

#Get users who have a first name that starts with H
sq3 = """ SELECT * FROM users WHERE first_name LIKE 'H%';"""
run_query(sq3)

# Get all .edu email addresses... just the email addresses
sq4 = """ SELECT * FROM users WHERE email LIKE '%.edu'
          ;"""
run_query(sq4)
## Q3 Your function ends here - Any code outside of these start/end markers won't be graded

"""## Q4 GROUP BY and HAVING - 5 points

Time to practice some GROUP BY and HAVING operations. Please write and run queries that do the following:

GROUP BY application
* Find the top five venues that hosted the most events: Alias the count of events as 'events_hosted'. Also return the venue ID
* Get the number of events hosted in each month. You'll need to use `date_part()` in your select to select just the months. Alias this as 'month' and then the count of the number of events hosted as 'events_hosted'.
* Get the top five sellers who made the most commission. Alias their total commission made as 'total_com'. Also get their average commission made and alias as 'avg_com'.  Be sure to also display the seller_id.  

HAVING application
* Using the same query as the last one, instead of getting the top five sellers get all sellers who have made a total commission greater than $4000.
* Using the same query as the first groupby, instead of returning the top five venues, return just the ID's of venues that have had greater than 60 events.

**Make sure to use the sq1, sq2, and sq3 as variables to store your queries in because those will specifically be evaluated**
"""

## Q4 Your function starts here
### GROUP BY application
# Find the top five venues that hosted the most events: Alias the count of events as 'events_hosted'. Also return the venue ID
sql_head(table_name='event')
sq1 = """ SELECT venue_id, COUNT(event_id) AS events_hosted
          FROM event
          GROUP BY venue_id
          ;"""
run_query(sq1)

# Get the number of events hosted in each month. You'll need to use `date_part()` in your select to select just the months.
# Alias this as 'month' and then the count of the number of events hosted as 'events_hosted'
# sql_head(table_name='event')
sq2 = """ SELECT date_part('month', start_time) AS month, COUNT(event_id) AS events_hosted
          FROM event
          GROUP BY month
          ;"""
run_query(sq2)

# Get the top five sellers who made the most commission. Alias their total commission made as 'total_com'.
# Also get their average commission made and alias as 'avg_com'. Be sure to also display the seller_id
sq3 = """ SELECT seller_id, SUM(commission) AS total_com, AVG(commission) AS avg_com
          FROM sales
          GROUP BY seller_id
          LIMIT 5
          ;"""
run_query(sq3)

### HAVING application
# Using the same query as the last groupby, instead of getting the top five sellers get all sellers who have made a total commission greater than $4000
sq4 = """ SELECT seller_id, SUM(commission) AS total_com, AVG(commission) AS avg_com
          FROM sales
          GROUP BY seller_id
          HAVING SUM(commission) > 4000
          ;"""
run_query(sq4)

# Using the same query as the first groupby, instead of returning the top five venues, return just the ID's of venues that have had greater than 60 events
sq5 = """ SELECT venue_id
          FROM event
          GROUP BY venue_id
          HAVING COUNT(event_id) > 60
          ;"""
run_query(sq5)
## Q4 Your function ends here - Any code outside of these start/end markers won't be graded

"""## Q5 JOIN - 5 points

Time for some joins. You've probably noticed by now that there is at least one relational key in each table, but some have more.  For example, sales has a unique sale id, listing id, seller id, buyer id, date id.  This allows you to link each sale to relevant information in other tables.  
**LIMIT each output to 5**

Please write queries to do the following items:

* Join information of users to each sale made.  
* Join information about each venue to each event.

**Make sure to use the sq1, sq2, sq3, and sq4 as variables to store your queries in because those will specifically be evaluated**
"""

## Q5 Your function starts here
sq1 = """ SELECT * FROM sales
          LIMIT 5;"""
run_query(sq1)

sq2 = """ SELECT * FROM users
          LIMIT 5;"""
run_query(sq2)

get_column_names(table_name='users')

get_column_names(table_name='sales')

# Join users information to each sale
sq3 = """ SELECT *
          FROM sales
          JOIN users ON sales.buyer_id = users.user_id
          ;"""
run_query(sq3)

# For each event attach the venue information
sq4 = """ SELECT *
          FROM event
          JOIN venue ON event.venue_id = venue.venue_id
          ;"""
run_query(sq4)
## Q5 Your function ends here - Any code outside of these start/end markers won't be graded

"""## Q 6 Subqueries - 5 points

To wrap up let's do several subqueries. Please do the following:

* Get all purchases made by users of live in Arizona
* Get event information for all events that took place in a venue where the venue name ends with 'Stadium'.
* Get event information for all events where the total ticket sales were greater than $50,000.  

**Make sure to use the sq1, sq2, and sq3 as variables to store your queries in because those will specifically be evaluated**
"""

## Q6 Your function starts here
# Get all purchases from users who live in Arizona
# sql_head(table_name='users')
sq1 = """ SELECT * FROM sales
          WHERE buyer_id IN (SELECT user_id FROM users WHERE state = 'AZ')
          ;"""
run_query(sq1)

# Get event information for all events that took place in a venue where the name ended in 'Stadium'
sq2 = """ SELECT * FROM event
          WHERE venue_id IN (SELECT venue_id FROM venue WHERE venue_name LIKE '%Stadium')
          ;"""
run_query(sq2)

# Get event information where the total sales for that event were greater than $50000
# sql_head(table_name='sales')
sq3 = """ SELECT * FROM event
          WHERE event_id IN (SELECT event_id FROM sales GROUP BY event_id HAVING SUM(price_paid) > 50000)
          ;"""
run_query(sq3)

get_table_names()

get_column_names(table_name= 'date')

## Q6 Your function ends here - Any code outside of these start/end markers won't be graded